services:
  doutor-agenda-db:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=doutor_agenda
    volumes:
      - ./.postgres-data:/bitnami/postgresql

volumes:
  .postgres-data:
