import './globals.css'

import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'

import { Toaster } from '@/_components/ui/sonner'
import { ReactQueryProvider } from '@/_providers/react-query'

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    default: 'Doutor Agenda',
    template: '%s | Doutor Agenda',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${manrope.variable} antialiased`}>
        <ReactQueryProvider>
          <NuqsAdapter>{children}</NuqsAdapter>
          <Toaster position="bottom-center" richColors />
        </ReactQueryProvider>
      </body>
    </html>
  )
}
